import type { NextPage } from 'next'
import Head from 'next/head'
import Sidebar from '@/components/Sidebar'
import Center from '@/components/Center'


const Home: NextPage = () => {
  return (
    <div className='bg-gray-100 h-screen overflow-hidden'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex'>
        <Sidebar />
        <Center />

      </main>
    </div>
  )
}
export default Home